name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt
          targets: thumbv7em-none-eabi
      - run: cargo fmt --all -- --check
      - run: cargo clippy --workspace --all-targets --all-features -- -D warnings
      - run: cargo test --workspace --all-targets --all-features
      - run: cargo test -p kittens --doc --all-features
      - run: RUSTDOCFLAGS='-D warnings' cargo doc -p kittens --all-features --no-deps
      - run: cargo build -p kittens-no-std-fixture -p kittens-feature-unifier --target thumbv7em-none-eabi --release --bins

  rust-1-85:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.85.0
      - run: cargo +1.85.0 check -p kittens --no-default-features --features macros
      - run: cargo +1.85.0 check -p kittens --all-features
      - run: cargo +1.85.0 check -p kittens-renamed-dependency-fixture
